### ISSUE TITLE
How to run image?

### ISSUE THREAD

**Issue by DtPJ** [why-not-try-calmer/popos-docker#1]
Love your project and the idea of running Pop_OS within a container, but I am fairly new and not sure how to run the image. Everything I have tried I get an error “no command specified.” Any help in getting it running using docker compose would be appreciated.

Again, great work and thank you for making it available to others!

**Comment by why-not-try-calmer** [comment]
How about `docker run nycticoracs/pop_os bash `?

**Comment by DtPJ** [comment]
Thanks, Adrien.

'/bin/bash' did not work for some reason but 'bash' did. I have it up
running, but am unsure how to access the GUI. My apologies for the newbie
problems.

**Comment by why-not-try-calmer** [comment]
Have you looked into the "+xhost " trick that people usually use for that purpose? See https://stackoverflow.com/questions/43015536/xhost-command-for-docker-gui-apps-eclipse
